# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnaRyFPNRMNTWPvgquo_8zMpetw6JWP4
"""

# 上辺：10cm
# 下辺：20cm
# 高さ：5cm

# 公式：台形の面積 =（上辺＋下辺）× 高さ ÷ 2
x=(10+20)*5/2
print(str(x) + "cm")